### ISSUE TITLE
Link between Groups and Canton lost

### ISSUE THREAD

**Issue by PapillonAudrey** [digio-ch/pbs-healthcheck-core#105]
**Describe the bug**

Une grande partie des relations entre cantons et groupes sont perdues et l’outil "Abteilungen im Vergleich" est donc vide pour les régions/cantons concernés.   
![grafik](https://github.com/digio-ch/pbs-healthcheck-core/assets/113099749/ebb7b954-b3d4-42a3-a683-121caeabb3b6)

Il est tout à fait possible que cela soit lié à la nouvelle release MiData de mi-janvier.

**Comment by SebastianStorz** [comment]
Corresponds to: HC-244
