### ISSUE TITLE
Wrong link in resources for "Kursangebot" in "Erfolgslogik Kantonsebene"

### ISSUE THREAD

**Issue by PapillonAudrey** [digio-ch/pbs-healthcheck-core#106]
**Describe the bug**

In the card « Kursangebot », the resource linked to the question «In Zusammenarbeit mit anderen Kantonalverbänden bieten wir unseren Leitenden alle im Ausbildungsmodell vorgesehenen kantonalen Kurse an.» is not completed. A list is planned with MiData infos, but nothing can be seen.

![grafik](https://github.com/digio-ch/pbs-healthcheck-core/assets/113099749/5c357d03-ce6f-479d-a202-bd4d175c31c2)

**Comments**
It's not clear whether this is a new bug or whether it has been behaving incorrectly for some time.

**Comment by SebastianStorz** [comment]
Corresponds to: HC-243

**Comment by PapillonAudrey** [comment]
Closing was an error. I am discussing the next steps with the team.
