### ISSUE TITLE
Wrong numbers for the Biberstufe

### ISSUE THREAD

**Issue by tobijuon** [digio-ch/pbs-healthcheck-core#2]
Bei der Biberstufe der Abteilung "Pfadi St. Martin Buochs" wird eine falsche Anzahl Teilnehmende angezeigt (37 statt 64). Auch am folgendenden Tag stellte der AL denselben Fehler fest.
---
Mail von Spion vom 25.1.2021 an hc.pbs@db.scout.ch

**Comment by TaminoWalter** [comment]
Dieses Problem ist etwas komplexer als die anderen. Wir konnten auf die schnelle keine mögliche Ursache finden. Es könnte sich um ein eingabe Fehler handeln.
Wir können uns dieses Issue nochmal genauer anschauen und das abklären. Um die Fehlerursache Abzuklären schätze ich 1h

**Comment by tobijuon** [comment]
Geht gemäss Absprache in Ordnung. Ihr habt auch direkt die Freigabe, den Fehler zu beheben, wenn es zusammen maximal 3h dauert.
