### ISSUE TITLE
QUAP Zusatzanforderungen für Kantons- und Bundesebene

### ISSUE THREAD

**Issue by tobijuon** [digio-ch/pbs-healthcheck-core#20]
- Das QUAP Feature hat eine Zusammenfassungsansicht (Für übergeordnete ebenen)
- Kantonalverbände und die Bundesebene können sich einloggen
- Kantonalverbände haben eine eigene Grafenansicht mit anderen Aspekten und Fragen
- Kantonalverbände und die Bundesebene haben zugriff auf die QUAP Komponente von untergeordneten ebenen, falls diese es erlauben

**Comment by vouillamoz** [comment]
@PapillonAudrey wurde erledigt.
