### ISSUE TITLE
Date-Picker shows also the last day of the month as a selectable date

### ISSUE THREAD

**Issue by TaminoWalter** [digio-ch/pbs-healthcheck-core#24]
**Describe the bug**

Since November 2020 the Date-Picker also shows selectable dates like "31. Dez 20" or "28. Feb 21".

**Reproducing the bug**

1. Log in application
2. Open the Date-Picker interface
3. Wrong dates are displayed

**Expected behavior**

Only the first of all past months should be displayed.

**Actual behavior**

There are also other dates selectable

**Environment**

- Version: latest
- Environment: Latest Live Version

**Additional context**

The issue seems to be caused by changes from November 2020

**Comment by tobijuon** [comment]
@TaminoWalter
Thank you for reporting this bug.
As the application is still usable and no impossible dates are shown, we would like to prioritise the other requests and put this one on hold.

**Comment by vouillamoz** [comment]
@PapillonAudrey Wurde gelöst.
