### ISSUE TITLE
Sprache inkonsistent in Chrome

### ISSUE THREAD

**Issue by tobijuon** [digio-ch/pbs-healthcheck-core#3]
Problem tritt nur in Chrome auf:
Wenn ich mich als Coach bei meiner Abteilung einlogge, erscheinen die einen Worte auf deutsch (Teilnehmende, Leitende) und andere auf Französisch (Louveteau, Eclaireur...).
Ich wechsle häufiger die Sprache in der MiData, kann aber nicht nachvollziehen, weshalb es nicht stringent ist.
![image](https://user-images.githubusercontent.com/55490822/108674559-c6687780-74e5-11eb-83a1-7d00c18d84d9.png)

**Comment by TaminoWalter** [comment]
Im Front- und Backend wird eine andere Methode verwenden um die Sprache festzustellen. Wir müssten das vom Frontend aus Synchronisieren.
Estimation: 3h

**Comment by tobijuon** [comment]
Thanks for the fix!
