### ISSUE TITLE
Wenn nur "Adressverwalter" als Rolle ausgewählt wurde, taucht der Leiter nicht im Leitungsteam auf

### ISSUE THREAD

**Issue by xcrookedxedgex** [digio-ch/pbs-healthcheck-core#34]
**Describe the bug**

Wenn in der Midata eine Leitungsperson in einer Gruppe erfast ist (bspw. Biber) und nur die Rolle "Adressverwalter" innehat, taucht diese im Healthcheck nicht auf. Es muss eine zusätzliche Rolle (bspw. Mitleiter*in) erfasst werden. 

**Reproducing the bug**
1. Leiter in einer Gruppe nur mit der Rolle "Adressverwalter" hinzufügen.
2. Health Check öffnen
3. Leiter taucht nicht in der Liste auf.
4. 
**Expected behavior**

Die Leitungsperson sollte auch auftauchen, wenn nur die Rolle Adressverwalter erfasst ist. 

**Actual behavior**

Leitperson taucht nicht auf, wenn nur die Rolle Adressverwalter erfasst ist. 

**Environment**

- Version: latest, v1.2.3, git sha hash
- Environment: Latest Live Version, Docker, Mac/Windows/Linux Version ...

**Additional context**

**Comment by carlobeltrame** [comment]
Dafür müsste man wohl Adressverwalter*in in https://github.com/digio-ch/pbs-healthcheck-core/blob/develop/src/Service/Aggregator/WidgetAggregator.php#L27..L62 ergänzen und dann alle bestehenden Aggregationen im HC löschen, damit sie über Nacht neu berechnet werden.

**Comment by tobijuon** [comment]
Vielen Dank für die Rückmeldung. Ich gehe allerdings nicht davon aus, dass jemand mit der Rolle "Adressverwalter*in" als Leiter*in angezeigt werden **soll**. In meinem Verständnis sollte ein*e Adressverwalter*in, die auch Leiter*in ist in der MiData beide Rollen haben. Es gibt – zumindest auf Abteilungsebene – viele Fälle, bei denen kantonale/regionale PowerUser oder Coaches diese Rolle erhalten, um Support zu leisten oder selbst Adressanpassungen vorzunehmen. Diese sollten nicht im HealthCheck erscheinen. Gerne spiegle ich dies noch mit dem ProductOwner der MiData und komme dann darauf zurück.

**Comment by xcrookedxedgex** [comment]
> Vielen Dank für die Rückmeldung. Ich gehe allerdings nicht davon aus, dass jemand mit der Rolle "Adressverwalterin" als Leiterin angezeigt werden soll. In meinem Verständnis sollte eine Adressverwalterin, die auch Leiter*in ist in der MiData beide Rollen haben. Es gibt – zumindest auf Abteilungsebene – viele Fälle, bei denen kantonale/regionale PowerUser oder Coaches diese Rolle erhalten, um Support zu leisten oder selbst Adressanpassungen vorzunehmen. Diese sollten nicht im HealthCheck erscheinen. Gerne spiegle ich dies noch mit dem ProductOwner der MiData und komme dann darauf zurück.

Das macht natürlich Sinn. Daran habe ich gar nicht gedacht. Dann weiss ich aber jetzt wieso das so ist, und kann das in Zukunft beachten. Danke euch!

**Comment by tobijuon** [comment]
Gerne, danke dir fürs Mitdenken!
