### ISSUE TITLE
Upcoming prolongation of J+S-qualifications

### ISSUE THREAD

**Issue by carlobeltrame** [digio-ch/pbs-healthcheck-core#38]
In MiData, some J+S qualifications will be [prolonged soon](https://github.com/hitobito/hitobito/issues/1344). This extraordinary prolongation has already taken place via a silent data migration in the NDS / SportDB, and MiData will attempt to mirror that change.

No history entries or new qualifications will be created in MiData. From the point of view of HealthCheck, one day the relevant existing qualifications will simply be valid for a year longer than they used to be. This might lead to problems or inconsistencies with the "mirrored" midata_* tables and especially the aggregated tables in HealthCheck.

The criteria that prolonged qualifications need to meet are based on the courses that granted the qualifications, and currently the HealthCheck doesn't know anything about this connection between courses and qualifications (and it doesn't need to, either, as a data visualization tool). So there is no easy way of doing a similar data migration in HealthCheck.

I think currently, the easiest option in HealthCheck would be to completely truncate the database once after the change has taken place in MiData, and then wait for the nightly re-import of all updated data and prolonged qualifications. Any other ideas?

**Comment by tobijuon** [comment]
Thanks @carlobeltrame for the input!
"soon" being the 23.11.2021
@TaminoWalter any idea how to solve this?

**Comment by TaminoWalter** [comment]
Thanks for your concern.

We won't need a migration or anything. All midata_* entities in HC get synced automatically by the id (every morning). This means that also the qualifications in HC get updated when they get updated inside MiData.

**Comment by tobijuon** [comment]
Sounds good, I will close this issue – and hope, we will not have to reopen it.
