### ISSUE TITLE
Neue Layer im Kartenwidget: Treffpunkte der Abteilungen

### ISSUE THREAD

**Issue by taruxtin** [digio-ch/pbs-healthcheck-core#47]
### Beschreibung
Das Kartenwidget wird um einen weiteren Layer erweitert, mit der die auf der MiData eingetragenen Treffpunkte auf der Karte visualisiert werden können. Es handelt sich dabei um die Treffpunkte, die ebenfalls im Pfadifinder angezeigt werden: https://pfadi.swiss/de/go/mitmachen/

Dieses Feature war ursprünglich Teil von #1, wurde aber zugunsten von anderen Arbeiten nicht umgesetzt. 

### Akzeptanzkriterien
1. Die Treffpunkte werden tagesaktuell aus der MiData übernommen.
2. Die Treffpunkte können in einem eigenen Layer ausgewählt / abgewählt werden (wie bisher die "Wohnorte"). Sie sind standardmässig aktiviert.
3. Beim Auswählen des Layers (nach dem es abgewählt wurde) wird, im Falle, dass keine Treffpunkte hinterlegt wurden, die folgende Nachricht angezeigt: "XYZ".

### Details
- Übersetzung: Treffpunkte / Lieux de rendez-vous / Punti d'incontro
- 
### Offene Fragen
1. Was nutzen wir für ein Icon zur Visualisierung? -> bestehendes Icon aus Mockup, aber Farbe, die nicht vorbelastet ist (durch Stufe)

### Mockups
![grafik](https://user-images.githubusercontent.com/7249623/107439321-264c3f00-6b32-11eb-8f46-c154b46e91af.png)

**Comment by vouillamoz** [comment]
@taruxtin Kommen die Treffpunkte einer Abteilung mittlerweile über die Schnittstelle? Kannst du den MiData-Issue hier noch verlinken?

**Comment by vouillamoz** [comment]
HC-233

**Comment by vouillamoz** [comment]
@PapillonAudrey can we close this issue?
