### ISSUE TITLE
Wrong Data and Visualization in the Widget "Anzahl Eintritte- und Austritte"

### ISSUE THREAD

**Issue by taruxtin** [digio-ch/pbs-healthcheck-core#48]
**Describe the bug**
The Widget "Anzahl Eintritte- und Austritte" does show incorrect data. There seems to be a problem with data aggregation. Some months are doubled.

**Reproducing the bug**

1. Log in application
2. Choose a group
3. Open the timespan-view starting with the beginning of the last year

**Expected behavior**

Every month hast one entry / bar.

**Actual behavior**

Some months are twice (sometimes with the same, sometimes with different values)
![grafik](https://user-images.githubusercontent.com/7249623/184537638-2a288b50-4060-484c-8e69-ee5ac744abde.png)
 
**Environment**

- Version: v 1.2.1 in production
- Environment: in production / recent Firefox

**Comment by vouillamoz** [comment]
@PapillonAudrey Wurde gefixt.
