### ISSUE TITLE
IP blocking?

### ISSUE THREAD

**Issue by PapillonAudrey** [digio-ch/pbs-healthcheck-core#50]
Bug-Report von Olipo:
Es ist mir aktuell nicht möglich, mich in HealthCheck einzuloggen. Ich kann den Oauth-Flow starten, jedoch kommt gemäss Netzwerktab bei 
POST https://[hc.scout.ch](http://hc.scout.ch/)/api/v1/oauth/v2/code die Antwort 403 Forbidden mit der message "Client IP 157.143.51.97 blocked" zurück. Ich werde dann wieder zum Login-Screen umgeleitet. Mir ist nicht klar, warum meine IP blockiert sein soll, noch war mir bewusst, dass ein IP-Blocking-Feature implementiert ist. Ich habe das ganze auch in einem Incognito-Fenster probiert mit demselben Resultat.

Umgebung
- Ubuntu Firefox 104.0.1
- Ubuntu Chromium 105.0.5195.52

**Comment by vouillamoz** [comment]
@PapillonAudrey ist das hier noch aktuell?

**Comment by PapillonAudrey** [comment]
> @PapillonAudrey ist das hier noch aktuell?

Ich muss das checken. Komme wieder mit einer Antwort.
