### ISSUE TITLE
Add new PO as Admin-Role on HC

### ISSUE THREAD

**Issue by vouillamoz** [digio-ch/pbs-healthcheck-core#52]
HalthCheck Projekt has a new PO. Please
- Remove the current PO (tobias.juon@pbs.ch) as Admin-Role on HC-Core
- Add new PO (audrey.jordan@scout-valais.ch) as Admin-Role on HC-Core

Changes on Github-Team was already done.

**Comment by vouillamoz** [comment]
@PapillonAudrey bitte testen und abnehmen.

**Comment by PapillonAudrey** [comment]
Nicht ok : ich kann nur meine Abteilung sehen.

**Comment by TaminoWalter** [comment]
@PapillonAudrey I had a mistake in the configuration, please retry

**Comment by PapillonAudrey** [comment]
Alles gut !
Tested and approved.
