### ISSUE TITLE
Dauer der Freigabe von 1 Monat auf 12 Monate erweitern

### ISSUE THREAD

**Issue by taruxtin** [digio-ch/pbs-healthcheck-core#7]
### Summary
Der Zugriff nach der Freigabe durch eine Person mit der Rolle Abteilungsleiter oder Abteilungsleiter Stv. ist aktuell auf einen Monat beschränkt. Neu soll er auf 12 Monate beschränkt sein.

### Motivation & Use-Case
Der Zugriff auf eine Abteilung kann von Personen  mit der Rolle Abteilungsleiter oder Abteilungsleiter Stv. für alle Personen mit einem MiData-Account freigegeben werden. Dieser ist dann auf einen Monat beschränkt. Es hat sich gezeigt, dass dies in der Praxis ein zu kurzer Zeitraum ist und es zu viel Aufwand (und Hin- und Her kommt), weil die Freigaben immer und immer wieder erneuert werden müssen. Aus diesem Grund soll der Zugriff neu 12 Monate anstatt 1 Monat gültig sein.

Der Entzug der Freigabe durch den Freigebenden soll weiterhin möglich sein.

**Comment by tobijuon** [comment]
@TaminoWalter leider nicht testbar für mich, aber ich gehe davon aus, dass das funktioniert hat.

**Comment by tobijuon** [comment]
There seems to have occurred a new problem with giving someone else viewing rights.
