### ISSUE TITLE
Stage - Healthcheck is down

### ISSUE THREAD

**Issue by PapillonAudrey** [digio-ch/pbs-healthcheck-core#81]
**Describe the bug**
HC-stage is down for 2 days.
When trying to reach it via firefox the following message appears:

    Fehler: Netzwerk-Zeitüberschreitung

    Beim Verbinden mit hc-stage.cust.digio.ch trat ein Fehler auf.

    Die Website könnte vorübergehend nicht erreichbar sein, versuchen Sie es bitte später nochmals.
    Wenn Sie auch keine andere Website aufrufen können, überprüfen Sie bitte die Netzwerk-/Internetverbindung.
    Wenn Ihr Computer oder Netzwerk von einer Firewall oder einem Proxy geschützt wird, stellen Sie bitte sicher, dass Firefox auf das Internet zugreifen darf.

And below is the message sent by UpTime robot.
![grafik](https://user-images.githubusercontent.com/113099749/208374509-8e5c0559-59c9-46e2-800b-43386a8939cf.png)

**Comment by vouillamoz** [comment]
@PapillonAudrey issue wurde behoben.
