### ISSUE TITLE
Qualifications are outdated for some leaders

### ISSUE THREAD

**Issue by Kordishal** [digio-ch/pbs-healthcheck-core#85]
**Describe the bug**

Two leaders within the health check have an outdated qualification listed. It says their J+S Leiter*in LS/T Kinder (KS) is expired. However, they have since both passed the J+S Lagerleiter*in LS/T. Both these qualifications are listed in MiData.

I can forward you the names of both the leaders via email if necessary.

All other leaders have all of their qualifications listed correctly.

**Reproducing the bug**

1. The display of the leaders and their qualifications shows outdated information for two leaders.

**Environment**

- Version: Version 1.3.0|Letzter Import am: 30.05.2023
- Environment: Latest Live Version

**Comment by PapillonAudrey** [comment]
I discovered this bug for other leaders.

For some leaders, the correct expiry date is transferred to HC. For some other leaders an "expired expiry" date is transferred.
I could not find a difference in MiData between the leaders with the right date in HC and those with the wrong one. 
For example, two leaders extended their qualification at the same time, but for one the change was not taken into account in HC.

I can also provide details for those examples.

**Comment by vouillamoz** [comment]
@PapillonAudrey can we close this issue?

**Comment by Kordishal** [comment]
I can't see the error on my end anymore.
